### PR TITLE
fix: create separate intercepters for /create and /summary endpoints

### LINKED ISSUE #1: Setup Azure / CI
* Create Azure web app
* Add GitHub action to deploy to Azure

### PR DESCRIPTION
**Pull request by JackieSL1**
# Description

**NOTE: This should only be merged AFTER https://github.com/JackieSL1/mini-survey-monkey/pull/70 is merged**

The SurveyStateInterceptor wasn't filtering out requests. I believe this was because Spring was injecting the same dependency twice, making both use the same filtering rules.

This adds two separate interceptor classes to avoid this issue.

## Issues

closes #1

# How to test

Manuals test:
1. Create a Survey
2. Try to go to "localhost:8080/summary/1". You should get an error
3. Open the survey
4. Now, try to go back to "localhost:8080/create/1". You should get an error

Integration tests:
* Run `mvn test`

# Checklist
**I've added tests**
- [x] Yes
- [ ] No 

**I've updated the DB schema and UML diagram**
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by BraedenKloke — CHANGES_REQUESTED** [review]
# Issue
**My only issue is that there is a lot of code duplication between the `CreateInterceptor` and `SummaryInterceptor`.**

I liked the `SurveyStateInterceptor` design, but perhaps, for this project, the `PageInterceptor` design is better since we lack expertise in Spring to understand whats going on under the hood.

# Change request
**I would suggest making an abstract class `PageInterceptor` that `CreateInterceptor` and `SummaryInterceptor` can inherit from.** 

This will make is easier for us to build future page interceptors.

**Comment by BraedenKloke** [comment]
> # Issue
> **My only issue is that there is a lot of code duplication between the `CreateInterceptor` and `SummaryInterceptor`.**
> 
> I liked the `SurveyStateInterceptor` design, but perhaps, for this project, the `PageInterceptor` design is better since we lack expertise in Spring to understand whats going on under the hood.
> 
> # Change request
> **I would suggest making an abstract class `PageInterceptor` that `CreateInterceptor` and `SummaryInterceptor` can inherit from.**
> 
> This will make is easier for us to build future page interceptors.

@JackieSL1, let me know if you want me to take a crack at building the abstract class `PageInterceptor`.

I would be happy to build off this branch. :smile:

**Comment by JackieSL1** [comment]
> > # Issue
> > **My only issue is that there is a lot of code duplication between the `CreateInterceptor` and `SummaryInterceptor`.**
> > I liked the `SurveyStateInterceptor` design, but perhaps, for this project, the `PageInterceptor` design is better since we lack expertise in Spring to understand whats going on under the hood.
> > # Change request
> > **I would suggest making an abstract class `PageInterceptor` that `CreateInterceptor` and `SummaryInterceptor` can inherit from.**
> > This will make is easier for us to build future page interceptors.
> 
> @JackieSL1, let me know if you want me to take a crack at building the abstract class `PageInterceptor`.
> 
> I would be happy to build off this branch. 😄

Sure @BraedenKloke ! I considered DRYing up the logic while I was making the new class but it didn't seem worth with only two of them. We'll probably need to add more interceptors in the future, so I think doing the abstraction now will make that easier.

**Comment by BraedenKloke** [comment]
@JackieSL1 - ok, let me take a crack at building the abstract class.

**Review by BraedenKloke — APPROVED** [review]
@JackieSL1, I was able to easily create an abstract class `PageInterceptor`.

Tests pass.

If you are happy with the design, feel free to merge away!

**Comment by JackieSL1** [comment]
> @JackieSL1, I was able to easily create an abstract class `PageInterceptor`.
> 
> Tests pass.
> 
> If you are happy with the design, feel free to merge away!

Design looks great!

**Pull request merged**
