### PR TITLE
Add survey filtering by user

### LINKED ISSUE #101: find all surveys by user
Issue #81 depends on this.

### PR DESCRIPTION
**Pull request by JackieSL1**
# Description

When a user visits their `/home` page, they only see surveys they've created.

- **NOTE: This should only be merged after #88** 

## Issues

- closes #101 

# How to test

Manual test:
1. Create two users, user1 and user2
2. Create a survey with user1
3. Login to user2 - you shouldn't be able to see user1's survey

Integration tests:
* Run `mvn test`

# Checklist
**I've added tests**
- [x] Yes
- [ ] No

**I've updated the DB schema and UML diagram**
- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by BraedenKloke** [comment]
Will review and contribute to this later today.

I have a few quick suggestions that I can implement.

**Comment by BraedenKloke** [comment]
Reviewing now.

**Review by BraedenKloke — APPROVED** [review]
Looks good.

**Please review my commits before merging.**

**I don't like how much duplication there is between htmlContains and htmlNotContains.** We could add a boolean value to the parameters but then I feel we are starting to overload the method ... not sure how to design it at this time. We are close to the end of the project so let's keep it as it.

**Comment by JackieSL1** [comment]
> Looks good.
> 
> **Please review my commits before merging.**
> 
> **I don't like how much duplication there is between htmlContains and htmlNotContains.** We could add a boolean value to the parameters but then I feel we are starting to overload the method ... not sure how to design it at this time. We are close to the end of the project so let's keep it as it.

Your changes look good!

I agree about the amount of duplication between the two methods being unnecessarily high. I think a nicer design might be to encapsulate the setup and execution of actions, such as creating a survey or visiting one, as methods we can reuse.  Those methods could then return an MvcResult which would let us use the existing Hamcrest marchers with them. I'm happy to leave it as is too.

**Pull request merged**
